// ─── Export Utilities ─────────────────────────────────────────────────────────
import type { GraphAssignment } from '../types/graph'
import type { EnablementResource } from '../types/enablement'

type CsvCell = string | number | boolean | null | undefined
type CsvRow = CsvCell[]

export function downloadCsv (rows: CsvRow[], filename: string) {
  const csv = rows
    .map(r => r.map(c => `"${(c ?? '').toString().replace(/"/g, '""')}"`).join(','))
    .join('\n')
  trigger(new Blob([csv], { type: 'text/csv' }), filename)
}

export function downloadText (text: string, filename: string) {
  trigger(new Blob([text], { type: 'text/plain' }), filename)
}

export function downloadHtml (html: string, filename: string) {
  trigger(new Blob([html], { type: 'text/html' }), filename)
}

function trigger (blob: Blob, filename: string) {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  a.click()
}

export function assignmentsToCsv (assignments: GraphAssignment[]): CsvRow[] {
  const rows: CsvRow[] = [['Name', 'Email / ID', 'Type', 'Principal ID']]
  for (const a of assignments) {
    rows.push([a.principalDisplayName, a.emailOrId, a.principalType, a.principalId])
  }
  return rows
}

export function enablementToHtml (resources: EnablementResource[], title = 'Litera One Enablement Resources') {
  const cards = resources.map(r => `
    <div class="card">
      <span class="tag type-${r.type}">${r.type}</span>
      <h3>${r.icon} ${r.title}</h3>
      <p>${r.description}</p>
      <a href="${r.url}" target="_blank">↗ Open Resource</a>
    </div>`).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; color: #1e293b; background: #f8fafc; }
    h1 { color: #0f172a; margin-bottom: 1.5rem; font-size: 2rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
    .card { background: #fff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 1.25rem; }
    .card h3 { margin: .5rem 0; font-size: 1rem; }
    .card p { color: #64748b; font-size: .875rem; margin: .5rem 0 .75rem; line-height: 1.5; }
    .card a { color: #2563eb; text-decoration: none; font-weight: 600; font-size: .875rem; }
    .card a:hover { text-decoration: underline; }
    .tag { display: inline-block; padding: 2px 8px; border-radius: 20px; font-size: .7rem; font-weight: 700; text-transform: uppercase; letter-spacing: .5px; }
    .type-video { background: #fee2e2; color: #b91c1c; }
    .type-guide { background: #e0f2fe; color: #0369a1; }
    .type-doc { background: #dcfce7; color: #15803d; }
    .type-template { background: #ede9fe; color: #7c3aed; }
    footer { text-align: center; margin-top: 3rem; color: #94a3b8; font-size: .8rem; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="grid">${cards}</div>
  <footer>Generated by Litera One Manager Portal · ${new Date().toLocaleDateString()}</footer>
</body>
</html>`
}
